import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  await prisma.eTF.createMany({
    data: [
      {
        ticker: 'VWCE',
        isin: 'IE00B3RBWM25',
        name: 'Vanguard FTSE All-World UCITS ETF Acc',
        domicile: 'IE',
        exchange: 'XETRA',
        currency: 'EUR',
        ter: 0.0022,
        fundSizeEur: 46200000000n,
        isAccumulating: true,
        isUcits: true,
        indexTracked: 'FTSE All-World',
        assetClass: 'EQUITY',
        provider: 'VANGUARD',
        inceptionDate: new Date('2019-07-23'),
      },
      {
        ticker: 'VWRL',
        isin: 'IE00B3RBWM25',
        name: 'Vanguard FTSE All-World UCITS ETF Dist',
        domicile: 'IE',
        exchange: 'XETRA',
        currency: 'EUR',
        ter: 0.0022,
        fundSizeEur: 8100000000n,
        isAccumulating: false,
        isUcits: true,
        indexTracked: 'FTSE All-World',
        assetClass: 'EQUITY',
        provider: 'VANGUARD',
        inceptionDate: new Date('2012-06-22'),
      },
      {
        ticker: 'IWDA',
        isin: 'IE00B4L5Y983',
        name: 'iShares Core MSCI World UCITS ETF Acc',
        domicile: 'IE',
        exchange: 'XETRA',
        currency: 'EUR',
        ter: 0.002,
        fundSizeEur: 68400000000n,
        isAccumulating: true,
        isUcits: true,
        indexTracked: 'MSCI World',
        assetClass: 'EQUITY',
        provider: 'ISHARES',
        inceptionDate: new Date('2009-09-25'),
      },
      {
        ticker: 'EIMI',
        isin: 'IE00BKM4GZ66',
        name: 'iShares Core MSCI EM IMI UCITS ETF Acc',
        domicile: 'IE',
        exchange: 'XETRA',
        currency: 'EUR',
        ter: 0.0018,
        fundSizeEur: 19800000000n,
        isAccumulating: true,
        isUcits: true,
        indexTracked: 'MSCI Emerging Markets IMI',
        assetClass: 'EQUITY',
        provider: 'ISHARES',
        inceptionDate: new Date('2014-05-30'),
      },
      {
        ticker: 'SSAC',
        isin: 'IE00B44Z5B48',
        name: 'iShares MSCI ACWI UCITS ETF Acc',
        domicile: 'IE',
        exchange: 'XETRA',
        currency: 'EUR',
        ter: 0.002,
        fundSizeEur: 12300000000n,
        isAccumulating: true,
        isUcits: true,
        indexTracked: 'MSCI ACWI',
        assetClass: 'EQUITY',
        provider: 'ISHARES',
        inceptionDate: new Date('2011-10-21'),
      },
      {
        ticker: 'FWRA',
        isin: 'IE0007J13DV8',
        name: 'Invesco FTSE All-World UCITS ETF Acc',
        domicile: 'IE',
        exchange: 'XETRA',
        currency: 'EUR',
        ter: 0.0015,
        fundSizeEur: 3100000000n,
        isAccumulating: true,
        isUcits: true,
        indexTracked: 'FTSE All-World',
        assetClass: 'EQUITY',
        provider: 'INVESCO',
        inceptionDate: new Date('2023-01-18'),
      },
      {
        ticker: 'LCWD',
        isin: 'LU1781541179',
        name: 'Amundi MSCI World UCITS ETF Acc',
        domicile: 'LU',
        exchange: 'XETRA',
        currency: 'EUR',
        ter: 0.0012,
        fundSizeEur: 11800000000n,
        isAccumulating: true,
        isUcits: true,
        indexTracked: 'MSCI World',
        assetClass: 'EQUITY',
        provider: 'AMUNDI',
        inceptionDate: new Date('2018-02-20'),
      },
      {
        ticker: 'DPYA',
        isin: 'IE00BFM6T921',
        name: 'iShares Developed Markets Property Yield UCITS ETF USD (Acc)',
        domicile: 'IE',
        exchange: 'LSE',
        currency: 'USD',
        ter: 0.0059,
        fundSizeEur: 216000000n,
        isAccumulating: true,
        isUcits: true,
        indexTracked: 'FTSE EPRA Nareit Developed',
        assetClass: 'REAL_ESTATE',
        provider: 'ISHARES',
        inceptionDate: new Date('2018-05-10'),
      },
      {
        ticker: 'IWDP',
        isin: 'IE00B1FZSF77',
        name: 'iShares Developed Markets Property Yield UCITS ETF Dist',
        domicile: 'IE',
        exchange: 'XETRA',
        currency: 'EUR',
        ter: 0.0059,
        fundSizeEur: 1400000000n,
        isAccumulating: false,
        isUcits: true,
        indexTracked: 'FTSE EPRA Nareit Developed',
        assetClass: 'REAL_ESTATE',
        provider: 'ISHARES',
        inceptionDate: new Date('2006-11-01'),
      },
      {
        ticker: 'VAGF',
        isin: 'IE00BG47KH54',
        name: 'Vanguard Global Aggregate Bond UCITS ETF Acc',
        domicile: 'IE',
        exchange: 'XETRA',
        currency: 'EUR',
        ter: 0.001,
        fundSizeEur: 2900000000n,
        isAccumulating: true,
        isUcits: true,
        indexTracked: 'Bloomberg Global Aggregate',
        assetClass: 'BOND',
        provider: 'VANGUARD',
        inceptionDate: new Date('2019-02-07'),
      },
      {
        ticker: 'AVWS',
        isin: 'IE0003R8QK55',
        name: 'Avantis All World Equity UCITS ETF Acc',
        domicile: 'IE',
        exchange: 'XETRA',
        currency: 'EUR',
        ter: 0.0023,
        fundSizeEur: 890000000n,
        isAccumulating: true,
        isUcits: true,
        indexTracked: 'Custom - All World Value Tilt',
        assetClass: 'EQUITY',
        provider: 'AVANTIS',
        inceptionDate: new Date('2022-10-18'),
      },
      {
        ticker: 'IS3S',
        isin: 'IE00BF4RFH31',
        name: 'iShares MSCI World Small Cap UCITS ETF Acc',
        domicile: 'IE',
        exchange: 'XETRA',
        currency: 'EUR',
        ter: 0.0035,
        fundSizeEur: 5600000000n,
        isAccumulating: true,
        isUcits: true,
        indexTracked: 'MSCI World Small Cap',
        assetClass: 'EQUITY',
        provider: 'ISHARES',
        inceptionDate: new Date('2018-04-16'),
      },
      {
        ticker: '5MVL',
        isin: 'IE00BG0SKF03',
        name: 'iShares MSCI World Value Factor UCITS ETF Acc',
        domicile: 'IE',
        exchange: 'XETRA',
        currency: 'EUR',
        ter: 0.003,
        fundSizeEur: 2100000000n,
        isAccumulating: true,
        isUcits: true,
        indexTracked: 'MSCI World Enhanced Value',
        assetClass: 'EQUITY',
        provider: 'ISHARES',
        inceptionDate: new Date('2015-09-25'),
      },
      {
        ticker: 'AGGH',
        isin: 'IE00BDBRDM35',
        name: 'iShares Core Global Aggregate Bond UCITS ETF Acc',
        domicile: 'IE',
        exchange: 'XETRA',
        currency: 'EUR',
        ter: 0.001,
        fundSizeEur: 6200000000n,
        isAccumulating: true,
        isUcits: true,
        indexTracked: 'Bloomberg Global Aggregate',
        assetClass: 'BOND',
        provider: 'ISHARES',
        inceptionDate: new Date('2017-11-28'),
      },
    ],
    skipDuplicates: true,
  })

  console.log('Seeded 14 ETFs')
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
