import type { Metadata } from 'next'
// Relative import (test graph; vitest resolves relative paths only).
import { SITE_DESCRIPTION, SITE_NAME, SITE_URL } from '../constants'

const DEFAULT_TITLE = `${SITE_NAME} - Free tools for EU passive investors`

// Site-wide metadata (the root layout exports this). The title template frames
// child titles, e.g. "ETF Screener · Indexfolio".
export const rootMetadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: { default: DEFAULT_TITLE, template: `%s · ${SITE_NAME}` },
  description: SITE_DESCRIPTION,
  applicationName: SITE_NAME,
  alternates: { canonical: '/' },
  openGraph: {
    type: 'website',
    siteName: SITE_NAME,
    url: SITE_URL,
    title: DEFAULT_TITLE,
    description: SITE_DESCRIPTION,
    locale: 'en',
  },
  twitter: {
    card: 'summary_large_image',
    title: DEFAULT_TITLE,
    description: SITE_DESCRIPTION,
  },
}

// The shared OG image (generated by app/opengraph-image.tsx, served at
// /opengraph-image). Referenced explicitly because a page that sets its own
// openGraph stops Next from auto-cascading the root image. 1200x630 matches
// OG_SIZE in og.tsx.
const OG_IMAGE = {
  url: '/opengraph-image',
  width: 1200,
  height: 630,
  alt: `${SITE_NAME} - free tools for EU passive investors`,
}

// Per-page metadata in one call: title, description, canonical, and OG/Twitter
// (image included). Every content route uses this. `path` is site-root relative.
export function pageMetadata({
  title,
  description,
  path,
}: {
  title: string
  description: string
  path: string
}): Metadata {
  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type: 'website',
      siteName: SITE_NAME,
      locale: 'en',
      url: path,
      title,
      description,
      images: [OG_IMAGE],
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [OG_IMAGE.url],
    },
  }
}
