name: Bossman

run-name: '🤖 Bossman on ${{ github.ref_name }} by @${{ github.actor }}'

on:
  push:
    branches: [dev, main]

jobs:
  checks:
    uses: ./.github/workflows/checks.yml
    secrets: inherit

  deploy-web:
    needs: checks
    uses: ./.github/workflows/deploy-web.yml
    with:
      environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}
    secrets: inherit
