name: CI

run-name: '🔍 Checking PR #${{ github.event.pull_request.number }} — ${{ github.event.pull_request.title }}'

on:
  pull_request:
    branches: [main, dev]

jobs:
  checks:
    uses: ./.github/workflows/checks.yml
    secrets: inherit
